apiVersion: v1
kind: Service
metadata:
  name: urban-aura-nodeport
  labels:
    app: urban-aura
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30000
  selector:
    app: urban-aura


# kubectl create -f filename
# kubectl delete -f filename
# kubectl apply -f filename
# kubectl diff  -f filename

#minikube service urban-aura-nodeport --url