apiVersion: v1
kind: Pod
metadata:
  name: urban-aura
  labels:
    name: urban-aura
spec:
  containers:
  - name: urban-aura
    image: tarunbhardwajdeveloper/urban-aura:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx


# kubectl create -f filename
# kubectl delete -f filename
# kubectl apply -f filename
# kubectl diff  -f filename

