apiVersion: apps/v1
kind: Deployment
metadata:
  name: urban-aura
  namespace: dev
  labels:
    app: urban-aura
  annotations:
    'kubernetes.io/change-cause': 'Updated to port 8081'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: urban-aura
  template: 
    metadata:
      labels:
        app: urban-aura
    spec:
      containers:
        - name: urban-aura
          image: tarunbhardwajdeveloper/urban-aura:v1
          ports :
            - containerPort: 80
  strategy:
    type: RollingUpdate
 

# kubectl scale deploy urban-aura  --replicas=5
