services:
    urbanaura:
        image: urbanaura
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
        ports:
            - 80:80
