apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-storage-pod
  labels:
    app: empty-dir
spec:
  containers:
    - name: empty-dir
      image: busybox
      command:
        - sh
        - -c
        - sleep 3600 
      volumeMounts:
        - name: empty-dir-storage
          mountPath: /temp
    - name: empty-dir-read
      image: busybox
      command:
        - sh
        - -c
        - sleep 3600 
      volumeMounts:
        - name: empty-dir-storage
          mountPath: /temp
          readOnlt: true
  volumes:
    - name: empty-dir-storage
      emptyDir: {}

      # kubectl exec -t empty-dir-storage-pod -c empty-dir -- sh