apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-persist-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  local:
    path: /mnt/disks/local1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: 'kubernetes.io/hostname'
              operator: In
              values: [minikube]
   
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-persist-volume-claim 
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow

---

apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-storage-pod
  labels:
    app: empty-dir
spec:
  containers:
    - name: empty-dir-read
      image: busybox
      command:
        - sh
        - -c
        - sleep 3600 
      volumeMounts:
        - name: slow
          mountPath: /mnt/local
  volumes:
    - name: slow
      persistentVolumeClaim:
        claimName: local-persist-volume-claim

---

apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-storage-pod-2
  labels:
    app: empty-dir
spec:
  containers:
    - name: empty-dir-read
      image: busybox
      command:
        - sh
        - -c
        - sleep 3600 
      volumeMounts:
        - name: slow
          mountPath: /mnt/local
  volumes:
    - name: slow
      persistentVolumeClaim:
        claimName: local-persist-volume-claim


# minikube ssh
