apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: urban-aura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: urban-aura
  template: 
    metadata:
      labels:
        app: urban-aura
    spec:
      containers:
        - name: urban-aura
          image: tarunbhardwajdeveloper/urban-aura:v1
          ports :
            - containerPort: 80