export const products = [
  {
    id: 1,
    sku: "JEAN-001",
    name: "Slim Fit Denim Jeans",
    price: 1899,
    image: "https://plus.unsplash.com/premium_photo-1690820317332-b9729e6f8844?q=80&w=3387&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Clothing",
    size: ["30", "32", "34", "36"],
    color: ["Blue", " mediumblue"],
    brand: "DenimPro",
    description: "Stretchable slim fit jeans made from premium denim.",
    stock: 16,
    highlights: [
      'Hand cut and sewn locally',
      'Dyed with our proprietary colors',
      'Pre-washed & pre-shrunk',
      'Ultra-soft 100% cotton',
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
  },
  {
    id: 2,
    sku: "TSHIRT-002",
    name: "Classic Cotton T-Shirt",
    price: 799,
    image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
    category: "Clothing",
    size: ["S", "M", "L", "XL"],
    color: ["mediumblue", "Grey", "White"],
    brand: "UrbanWear",
    description: "100% cotton T-shirt with a classic fit.",
    stock: 42,
    highlights: [
      'Hand cut and sewn locally',
      'Dyed with our proprietary colors',
      'Pre-washed & pre-shrunk',
      'Ultra-soft 100% cotton',
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
  },
  {
    id: 3,
    sku: "BAG-003",
    name: "Travel Backpack",
    price: 1999,
    image: "https://images.unsplash.com/photo-1696219695041-8dddb603cd33?q=80&w=3388&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Accessories",
    size: ["Standard"],
    color: ["Black", "Green"],
    brand: "HikeMate",
    description: "Durable backpack with multiple compartments.",
    stock: 31,
    highlights: [
      'Hand cut and sewn locally',
      'Dyed with our proprietary colors',
      'Pre-washed & pre-shrunk',
      'Ultra-soft 100% cotton',
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
  },
  {
    id: 4,
    sku: "SHOE-004",
    name: "Running Sneakers",
    price: 2999,
    image: "https://images.unsplash.com/photo-1617603280856-0ecabba82e09?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Footwear",
    size: ["7", "8", "9", "10"],
    color: ["Black", "White"],
    brand: "RunPro",
    description: "Lightweight sneakers ideal for daily runs.",
    stock: 20,
    highlights: [
      'Hand cut and sewn locally',
      'Dyed with our proprietary colors',
      'Pre-washed & pre-shrunk',
      'Ultra-soft 100% cotton',
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
  },
  {
    id: 5,
    sku: "WATCH-005",
    name: "Smartwatch X2",
    price: 4599,
    image: "https://images.unsplash.com/photo-1719075596884-2020f827a8dd?q=80&w=3387&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Electronics",
    size: ["One Size"],
    color: ["Black", "Silver"],
    brand: "TechTime",
    description: "Smartwatch with heart rate and notification features.",
    stock: 14,
    highlights: [
      'Hand cut and sewn locally',
      'Dyed with our proprietary colors',
      'Pre-washed & pre-shrunk',
      'Ultra-soft 100% cotton',
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
  },
  {
    id: 6,
    sku: "HOODIE-006",
    name: "Zipper Hoodie",
    price: 1599,
    image: "https://images.unsplash.com/photo-1644055570578-ce9fc55cdfa5?q=80&w=3024&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Clothing",
    size: ["M", "L", "XL"],
    color: ["Black", "Gray"],
    brand: "WarmCore",
    description: "Comfortable cotton-blend hoodie with zip front.",
    stock: 25,
    highlights: [
      'Hand cut and sewn locally',
      'Dyed with our proprietary colors',
      'Pre-washed & pre-shrunk',
      'Ultra-soft 100% cotton',
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
  },
  {
    id: 7,
    sku: "HEADPHONES-007",
    name: "Wireless Headphones",
    price: 3499,
    image: "https://plus.unsplash.com/premium_photo-1680346529370-c940bd7536ad?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8V2lyZWxlc3MlMjBIZWFkcGhvbmVzJTIwbm8lMjBiYWNrZ3JvdW5kfGVufDB8fDB8fHww",
    category: "Electronics",
    size: ["One Size"],
    color: ["Black", "White"],
    brand: "SoundPeak",
    description: "Noise-cancelling wireless headphones with Bluetooth.",
    stock: 18,
    highlights: [
      'Hand cut and sewn locally',
      'Dyed with our proprietary colors',
      'Pre-washed & pre-shrunk',
      'Ultra-soft 100% cotton',
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
  },
  {
    id: 8,
    sku: "JACKET-008",
    name: "Leather Jacket",
    price: 4999,
    image: "https://images.unsplash.com/photo-1562895367-8f6d066442d1?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TGVhdGhlciUyMEphY2tldCUyMG5vJTIwYmFja2dyb3VuZHxlbnwwfHwwfHx8MA%3D%3D",
    category: "Clothing",
    size: ["M", "L", "XL"],
    color: ["Brown", "Black"],
    brand: "UrbanRider",
    description: "Genuine leather biker jacket with zip pockets.",
    stock: 10
  },
  {
    id: 9,
    sku: "SUNGLASS-009",
    name: "Aviator Sunglasses",
    price: 899,
    image: "https://images.unsplash.com/photo-1639736921924-1cc822b2b393?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8QXZpYXRvciUyMFN1bmdsYXNzZXMlMjBubyUyMGJhY2tncm91bmR8ZW58MHx8MHx8fDA%3D",
    category: "Accessories",
    size: ["One Size"],
    color: ["Gold", "Silver"],
    brand: "VisionX",
    description: "Classic aviator sunglasses with UV protection.",
    stock: 30,
    highlights: [
      'Hand cut and sewn locally',
      'Dyed with our proprietary colors',
      'Pre-washed & pre-shrunk',
      'Ultra-soft 100% cotton',
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
  },
  {
    id: 10,
    sku: "BOTTLE-010",
    name: "Insulated Water Bottle",
    price: 499,
    image: "https://plus.unsplash.com/premium_photo-1678282075115-de1836c1393d?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8SW5zdWxhdGVkJTIwV2F0ZXIlMjBCb3R0bGUlMjBubyUyMGJhY2tncm91bmR8ZW58MHx8MHx8fDA%3D",
    category: "Home & Kitchen",
    size: ["750ml"],
    color: ["Black", "Red", "Blue"],
    brand: "HydroFlow",
    description: "Keeps beverages hot or cold for hours.",
    stock: 50,
    highlights: [
      'Hand cut and sewn locally',
      'Dyed with our proprietary colors',
      'Pre-washed & pre-shrunk',
      'Ultra-soft 100% cotton',
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
  }
];
